AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
    LambdaFunction:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: VotaNet
        Handler: lambda_function.lambda_handler
        Runtime: python3.8
        MemorySize: 256
        Timeout: 300
        Role: !GetAtt LambdaRole.Arn
        Environment:
            Variables:
                DYNAMO_BD: !ImportValue DynamoPlatzi 
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        ManagedPolicyArns:
          - !ImportValue LambdaPolicyDynamo
          - !ImportValue LambdaPolicyEC2
          - !ImportValue LambdaPolicyCW
          - !ImportValue LambdaPolicyS3
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
